version: '3.9'


services:
  gunicorn:
    container_name: gunicorn
    build: 
      context: .
      network: host
    ports:
      - 8000:8000
    environment:
      - DEBUG=0
    env_file:
      - .env
    volumes:
      - ./firebaseCredentials.json:/app/firebaseCredentials.json
    